import math
import random
import time
from datetime import datetime

from .captcha_solver import solve_captcha_if_present
from .email_imap import get_initial_mail_count, handle_email_verification
from .web_actions import (
    click_button,
    click_login_continue_strict,
    goto_with_retry,
    input_email,
    input_password,
    need_register,
)
from .logger import get_logger_manager
from .utils import wait_for_url_change
from .constants import (
    MAX_CAPTCHA_FAILS,
    URL_CHANGE_TIMEOUT_MS,
)


# URL 状态机最大迭代次数
MAX_TOTAL_ITERATIONS = 50
# 单个 URL 状态最大重试次数
MAX_URL_RETRIES = 10
# MFA 最大重试次数
MAX_MFA_RETRIES = 3


def _bezier_mouse_move(page, x_end, y_end, duration_ms=None):
    """
    贝塞尔曲线鼠标移动，模拟真实人类轨迹。
    从当前位置移动到 (x_end, y_end)，带随机弧度和变速。
    """
    # 获取当前鼠标位置（用 JS 追踪，fallback 到随机起点）
    try:
        pos = page.evaluate("() => ({x: window._mouseX || 0, y: window._mouseY || 0})")
        x_start, y_start = pos["x"], pos["y"]
        if x_start == 0 and y_start == 0:
            x_start = random.randint(100, 500)
            y_start = random.randint(100, 400)
    except Exception:
        x_start = random.randint(100, 500)
        y_start = random.randint(100, 400)

    dist = math.hypot(x_end - x_start, y_end - y_start)
    if dist < 5:
        return

    if duration_ms is None:
        duration_ms = random.randint(80, 250) + int(dist * random.uniform(0.4, 1.0))

    # 随机控制点，制造弧线
    cx = (x_start + x_end) / 2 + random.uniform(-120, 120)
    cy = (y_start + y_end) / 2 + random.uniform(-120, 120)

    steps = max(8, int(dist / random.uniform(6, 12)))
    step_delay = duration_ms / steps / 1000  # 秒

    for i in range(1, steps + 1):
        t = i / steps
        # 缓入缓出 ease
        t_ease = t * t * (3 - 2 * t)
        bx = (1 - t_ease) ** 2 * x_start + 2 * (1 - t_ease) * t_ease * cx + t_ease ** 2 * x_end
        by = (1 - t_ease) ** 2 * y_start + 2 * (1 - t_ease) * t_ease * cy + t_ease ** 2 * y_end
        # 加微小抖动
        bx += random.uniform(-1.5, 1.5)
        by += random.uniform(-1.5, 1.5)
        page.mouse.move(bx, by)
        time.sleep(step_delay * random.uniform(0.6, 1.4))

    # 记录最终位置
    try:
        page.evaluate(f"() => {{ window._mouseX = {x_end}; window._mouseY = {y_end}; }}")
    except Exception:
        pass


def setup_logger(email_addr):
    """为每个账号设置日志（使用统一的日志管理器）"""
    logger_manager = get_logger_manager()
    return logger_manager.get_account_logger(email_addr)


def save_failure_log(logger, email_addr):
    """失败时记录标记（实际日志保存由 LoggerManager.record_result 处理）"""
    # 新的日志系统在 record_result 时自动保存失败日志
    # 这里只记录一个失败标记到当前 logger
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    logger.info(f"{'='*60}")
    logger.info(f"失败时间: {timestamp}")
    logger.info(f"账号: {email_addr}")
    logger.info(f"状态: 失败")
    logger.info(f"{'='*60}")


def log_summary(email_addr, success, duration_sec, extra_info="", stage="", iterations=0):
    """记录摘要到控制台"""
    status = "成功" if success else "失败"

    parts = [f"[{email_addr}]", status]
    if stage:
        parts.append(f"阶段:{stage}")
    if iterations > 0:
        parts.append(f"迭代:{iterations}")
    parts.append(f"耗时:{duration_sec:.0f}s")
    if extra_info:
        parts.append(extra_info)

    msg = " | ".join(parts)

    # 输出到控制台
    symbol = "✓" if success else "✗"
    print(f"[{symbol}] {msg}")


def console_log(email_addr, message, level="info"):
    """统一的控制台输出格式"""
    short_email = email_addr.split("@")[0]
    prefix = {
        "info": "→",
        "success": "✓",
        "warning": "⚠",
        "error": "✗"
    }.get(level, "→")
    print(f"[{short_email}] {prefix} {message}")


# 风控检测关键词
RISK_SIGNATURES = [
    "网络连接失败",
    "操作失败",
    "PRECHECK",
    "cap_too_many_attempts",
    "208075",
    "208061",
    "认证失败，请刷新页面后重试",
    "$e.execute is not a function",
    # CloudFront CDN 层 403 拦截
    "403 ERROR",
    "The request could not be satisfied",
    "Generated by cloudfront",
    # IP 地区限制（美国等）
    "无法为该地区的用户提供服务",
    "200004431",
    "300010",
]

# 临时性错误，点击"已知晓"后可重试，不算严重风控
RETRIABLE_SIGNATURES = [
    "300010",
]

# IP 级别拦截，直接失败不重试
FATAL_SIGNATURES = [
    "403 ERROR",
    "The request could not be satisfied",
    "Generated by cloudfront",
    "无法为该地区的用户提供服务",
    "200004431",
    "PRECHECK",
]


def _handle_captcha_result(captcha_result, captcha_fail_count, email_addr, logger):
    """
    处理验证码结果的统一逻辑

    Returns:
        tuple: (should_stop, new_fail_count, stop_reason)
        - should_stop: 是否应该停止流程
        - new_fail_count: 更新后的失败计数
        - stop_reason: 停止原因 ("rate_limited" / False / None)
    """
    if captcha_result == "rate_limited":
        console_log(email_addr, "IP被风控，需更换代理", "error")
        logger.error("IP 被风控，请更换代理或等待后重试")
        return True, captcha_fail_count, "rate_limited"

    if captcha_result is False:
        captcha_fail_count += 1
        console_log(email_addr, f"验证码失败 {captcha_fail_count}/{MAX_CAPTCHA_FAILS}", "warning")
        logger.warning(f"验证码处理失败 ({captcha_fail_count}/{MAX_CAPTCHA_FAILS})")
        if captcha_fail_count >= MAX_CAPTCHA_FAILS:
            logger.error("验证码连续失败次数过多")
            return True, captcha_fail_count, False
        return False, captcha_fail_count, None

    # 成功，重置计数
    return False, 0, None


def _is_page_blank(page, logger=None):
    """检测页面是否白屏"""
    try:
        body = page.query_selector("body")
        if not body:
            return True
        text = body.inner_text().strip()
        # 白屏：body 为空或只有很少内容
        if len(text) < 50:
            # 再检查是否有可见元素
            visible_elements = page.query_selector_all("button, input, a, img")
            visible_count = sum(1 for el in visible_elements if el.is_visible())
            if visible_count < 3:
                if logger:
                    logger.info(f"检测到白屏: text_len={len(text)}, visible_elements={visible_count}")
                return True
        return False
    except Exception as e:
        if logger:
            logger.info(f"_is_page_blank 异常: {e}")
        return False


def _has_risk_error(page, logger=None):
    """检查页面是否有风控错误"""
    try:
        body = page.query_selector("body")
        text = body.inner_text() if body else ""
        has_risk = any(sig.lower() in text.lower() for sig in RISK_SIGNATURES)
        if has_risk:
            if logger:
                logger.info("检测到风控错误")
        return has_risk, text
    except Exception as e:
        if logger:
            logger.info(f"_has_risk_error 异常: {e}")
        return False, ""


def _tick_agreement_checkbox(page, email_addr=None, logger=None):
    """
    勾选注册页面的"创建账户即表示您同意币安"复选框。
    币安用自定义组件，复选框是文字左侧的方框图标。
    """
    try:
        # 方法1: 直接用 JS 找到复选框方框并点击
        # 币安的复选框通常是文字旁边的一个小方框（div/span/svg），在包含"创建账户"文字的行内
        clicked = page.evaluate("""() => {
            // 找包含关键文字的元素
            const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
            let textNode = null;
            while (walker.nextNode()) {
                if (walker.currentNode.textContent.includes('创建账户即表示') ||
                    walker.currentNode.textContent.includes('创建个人账户即表示')) {
                    textNode = walker.currentNode;
                    break;
                }
            }
            if (!textNode) return 'not_found';

            // 从文字节点向上找到行容器
            let row = textNode.parentElement;
            for (let i = 0; i < 8 && row; i++) {
                // 在这个容器里找 input[type=checkbox]
                const cb = row.querySelector('input[type="checkbox"]');
                if (cb) {
                    // 点击 checkbox 本身
                    cb.click();
                    if (cb.checked) return 'input_checked';
                    // 如果 click 没生效，尝试 dispatchEvent
                    cb.dispatchEvent(new MouseEvent('click', {bubbles: true}));
                    return 'input_dispatched';
                }
                // 找 role=checkbox 的元素
                const roleBox = row.querySelector('[role="checkbox"]');
                if (roleBox) {
                    roleBox.click();
                    return 'role_checkbox';
                }
                row = row.parentElement;
            }
            return 'no_checkbox_in_row';
        }""")

        if logger:
            logger.info(f"JS 勾选结果: {clicked}")

        if clicked and clicked not in ('not_found', 'no_checkbox_in_row'):
            if email_addr:
                console_log(email_addr, "勾选创建账户协议")
            page.wait_for_timeout(random.randint(300, 500))
            return True

        # 方法2: Playwright locator 点击复选框左侧的方框
        # 币安页面上复选框方框通常在文字的前一个兄弟元素
        checkbox_selectors = [
            "input[type='checkbox']",
            "[role='checkbox']",
            # 匹配 checkbox 容器 class
            "[class*='bn-checkbox']",
            "[class*='BnCheckbox']",
            "[class*='check-box']",
            "[class*='CheckBox']",
        ]
        for selector in checkbox_selectors:
            try:
                els = page.query_selector_all(selector)
                for el in els:
                    if el.is_visible():
                        el.click()
                        if logger:
                            logger.info(f"Playwright 点击复选框: {selector}")
                        if email_addr:
                            console_log(email_addr, "勾选创建账户协议")
                        page.wait_for_timeout(random.randint(300, 500))
                        return True
            except Exception:
                continue

        # 方法3: 用坐标点击——找到"创建账户"文字，点击其左侧的方框位置
        try:
            text_el = page.query_selector("text=创建账户即表示")
            if not text_el:
                text_el = page.query_selector("text=创建个人账户即表示")
            if text_el:
                box = text_el.bounding_box()
                if box:
                    # 方框在文字左侧，大约 x - 30 的位置，y 居中
                    click_x = box['x'] - 20
                    click_y = box['y'] + box['height'] / 2
                    page.mouse.click(click_x, click_y)
                    if logger:
                        logger.info(f"坐标点击复选框: ({click_x:.0f}, {click_y:.0f})")
                    if email_addr:
                        console_log(email_addr, "勾选创建账户协议")
                    page.wait_for_timeout(random.randint(300, 500))
                    return True
        except Exception as e:
            if logger:
                logger.info(f"坐标点击异常: {e}")

        if logger:
            logger.warning("未找到协议复选框")
        return False
    except Exception as e:
        if logger:
            logger.info(f"勾选复选框异常: {e}")
        return False


def _dismiss_error_popup(page, logger=None):
    """检查并点击"已知晓"等弹窗按钮，包括频率限制弹窗"""
    # 先检测是否有频率限制弹窗
    try:
        body_text = page.inner_text("body")
        if "frequency limit" in body_text.lower() or "208061" in body_text:
            if logger:
                logger.info("检测到频率限制弹窗 (208061)")
    except Exception:
        pass

    dismiss_btns = [
        "button:has-text('已知晓')",
        "button:has-text('Got it')",
        "button:has-text('OK')",
        "button:has-text('确定')",
        "button:has-text('关闭')",
        "button:has-text('Close')",
        "button:has-text('取消')",
        "button:has-text('Cancel')",
        "button:has-text('Try again')",
        "button:has-text('Retry')",
        "button:has-text('重试')",
        "[aria-label='Close']",
    ]
    for selector in dismiss_btns:
        try:
            btn = page.query_selector(selector)
            if btn and btn.is_visible():
                btn.click()
                msg = f"点击了关闭按钮: {selector}"
                if logger:
                    logger.info(msg)
                page.wait_for_timeout(random.randint(800, 1200))
                return True
        except Exception as e:
            msg = f"点击按钮 {selector} 失败: {e}"
            if logger:
                logger.info(msg)
    return False


def _check_url_change(page, url_before, action_name, wait_ms=1000, logger=None):
    """
    检查URL是否变化，用于检测页面跳转（使用统一的 wait_for_url_change）

    Args:
        page: Playwright page对象
        url_before: 操作前的URL
        action_name: 操作名称（用于日志）
        wait_ms: 最大等待时间（毫秒）
        logger: 日志对象

    Returns:
        新的URL
    """
    changed, url_after = wait_for_url_change(page, url_before, timeout_ms=wait_ms, logger=logger)
    if changed and logger:
        logger.info(f"URL变化 {action_name} 后: {url_before} -> {url_after}")
    elif not changed and logger:
        logger.info(f"{action_name} 后URL未变化: {url_before}")
    return url_after


def _wait_for_url_change(page, url_before, timeout_ms=5000, logger=None):
    """
    等待URL发生变化，用于关键操作后的页面跳转检测（使用统一的 wait_for_url_change）

    Args:
        page: Playwright page对象
        url_before: 操作前的URL
        timeout_ms: 最大等待时间（毫秒）
        logger: 日志对象

    Returns:
        tuple: (changed: bool, new_url: str)
    """
    return wait_for_url_change(page, url_before, timeout_ms=timeout_ms, logger=logger)


def _wait_for_page_response(page, url_before, timeout_ms=5000, logger=None):
    """
    等待页面响应：URL变化 或 验证码弹窗出现

    点击按钮后，页面可能：
    1. URL跳转到新页面
    2. 弹出验证码弹窗（URL不变）
    3. 显示错误提示

    Args:
        page: Playwright page对象
        url_before: 操作前的URL
        timeout_ms: 最大等待时间（毫秒）
        logger: 日志对象

    Returns:
        tuple: (response_type, new_url)
        - response_type: "url_changed" / "captcha" / "timeout"
        - new_url: 当前URL
    """
    # 验证码弹窗选择器（含 Binance 专用）
    captcha_selectors = [
        ".bcapc-popup",
        ".bcap-popup",
        ".bcap-modal",
        ".bs-modal",
        "#captcha-popup",
        "[class*='captcha']",
        "iframe[src*='captcha']",
        "[data-testid='captcha']",
        ".bds-modal",
    ]

    try:
        poll_interval = 200
        max_polls = timeout_ms // poll_interval

        for i in range(max_polls):
            page.wait_for_timeout(poll_interval)

            # 检查URL变化
            url_after = page.url
            if url_after != url_before:
                if logger:
                    logger.info(f"页面响应: URL变化 ({(i+1)*poll_interval}ms): {url_before} -> {url_after}")
                return "url_changed", url_after

            # 检查验证码弹窗
            for selector in captcha_selectors:
                try:
                    el = page.query_selector(selector)
                    if el and el.is_visible():
                        if logger:
                            logger.info(f"页面响应: 验证码弹窗出现 ({(i+1)*poll_interval}ms): {selector}")
                        return "captcha", url_after
                except Exception:
                    pass

        # 超时后再检查一次
        url_after = page.url
        if url_after != url_before:
            if logger:
                logger.info(f"页面响应: URL在超时边界变化: {url_before} -> {url_after}")
            return "url_changed", url_after

        if logger:
            logger.info(f"页面响应: 等待超时 ({timeout_ms}ms)，无变化")
        return "timeout", url_before

    except Exception as e:
        if logger:
            logger.error(f"_wait_for_page_response 异常: {e}")
        return "timeout", url_before


def login_with_url_state(page, email_addr, email_password, config, page_timeout=60000):
    # 设置日志
    logger = setup_logger(email_addr)
    start_time = datetime.now()
    short_email = email_addr.split("@")[0]
    console_log(email_addr, "开始登录")
    logger.info(f"开始登录: {email_addr}")

    api_key = config["openrouter_api_key"]
    model = config.get("models", [])
    imap_host = config["imap_host"]
    imap_port = config["imap_port"]
    login_start_url = config.get("login", {}).get("start_url", "https://accounts.binance.com/zh-CN/login")
    captcha_config = config.get("captcha", {})
    mfa_config = config.get("mfa", {})

    logger.info(f"登录URL: {login_start_url}")

    if not goto_with_retry(page, login_start_url, page_timeout=page_timeout):
        logger.error("登录页面加载失败")
        duration = (datetime.now() - start_time).total_seconds()
        log_summary(email_addr, False, duration, stage="页面加载", extra_info="加载失败")
        save_failure_log(logger, email_addr)
        return False

    initial_mail_count = get_initial_mail_count(imap_host, imap_port, email_addr, email_password)
    if initial_mail_count == "imap_auth_failed":
        logger.info("IMAP 认证失败，邮箱未开启 IMAP 或密码错误，无法读取邮件")
        save_failure_log(logger, email_addr)
        return "imap_auth_failed"
    consumed_codes = set()
    mfa_retry_count = 0
    last_stage = "login"  # 跟踪当前阶段
    captcha_fail_count = 0  # 验证码连续失败计数

    # URL 状态计数器
    url_retry_counts = {}  # {url_pattern: count}
    last_url_pattern = None

    def _get_url_pattern(url):
        """提取 URL 的状态模式"""
        if "/login/mfa" in url:
            return "login_mfa"
        elif "/login/password" in url:
            return "login_password"
        elif "/login/stay-signed-in" in url:
            return "login_stay_signed_in"
        elif "/login" in url and "/login/" not in url:
            return "login"
        elif "/my/" in url:
            return "dashboard"
        elif "authcenter/callback" in url:
            return "callback"
        else:
            return "other"

    for iteration in range(MAX_TOTAL_ITERATIONS):
        try:
            page.wait_for_timeout(1000)  # 固定等待1秒
            url = page.url
            url_pattern = _get_url_pattern(url)

            # 检查 URL 状态是否变化
            if url_pattern == last_url_pattern:
                url_retry_counts[url_pattern] = url_retry_counts.get(url_pattern, 0) + 1
                if url_retry_counts[url_pattern] >= MAX_URL_RETRIES:
                    logger.warning(f"URL 状态 {url_pattern} 重试次数超过 {MAX_URL_RETRIES} 次，停止")
                    console_log(email_addr, f"{url_pattern} 重试超限", "error")
                    duration = (datetime.now() - start_time).total_seconds()
                    log_summary(email_addr, False, duration, stage=last_stage, iterations=iteration+1, extra_info=f"{url_pattern}超限")
                    save_failure_log(logger, email_addr)
                    return False
            else:
                # URL 状态变化，重置该状态的计数
                url_retry_counts[url_pattern] = 1
                last_url_pattern = url_pattern

            msg = f"迭代 {iteration + 1} URL状态: {url_pattern} (重试 {url_retry_counts.get(url_pattern, 1)}/{MAX_URL_RETRIES})"
            logger.info(msg)

            # 更新当前阶段
            if "/login/mfa" in url:
                last_stage = "mfa"
            elif "/login/password" in url:
                last_stage = "password"
            elif "/login/stay-signed-in" in url:
                last_stage = "stay-signed-in"
            elif "/login" in url:
                last_stage = "login"

            # 检测浏览器错误页面（代理断开/网络问题），重新导航到登录页
            if "chrome-error://" in url or "about:blank" in url:
                logger.warning(f"检测到浏览器错误页面: {url}，重新导航到登录页...")
                try:
                    page.goto("https://accounts.binance.com/zh-CN/login", timeout=page_timeout)
                    page.wait_for_timeout(2000)
                except Exception as e:
                    logger.info(f"重新导航失败: {e}")
                continue

            # authcenter/callback 需要刷新才能继续跳转
            if "authcenter/callback" in url:
                logger.info("检测到 authcenter/callback，刷新页面...")
                try:
                    page.reload(timeout=10000)
                except Exception:
                    pass
                page.wait_for_timeout(2000)
                continue

            # 登录成功判断（优先于白屏检测，避免 dashboard 加载中被误判）
            if "/my/" in url or ("binance.com" in url and "login" not in url and "register" not in url and "authcenter" not in url):
                duration = (datetime.now() - start_time).total_seconds()
                logger.info("登录成功!")
                log_summary(email_addr, True, duration, stage="dashboard", iterations=iteration+1)
                return True

            # 检测白屏（仅在登录/注册页面检测）
            if _is_page_blank(page, logger):
                console_log(email_addr, "检测到白屏，刷新页面", "warning")
                logger.warning("检测到白屏，刷新页面")
                try:
                    page.reload(timeout=10000)
                except Exception:
                    pass
                page.wait_for_timeout(2000)
                continue

            has_risk, body_text = _has_risk_error(page, logger)
            if has_risk:
                msg = "检测到错误页面!"
                logger.warning(msg)
                logger.info(f"页面内容: {body_text[:500]}")

                # CloudFront 403 等 CDN 层拦截，直接失败不重试
                if any(sig.lower() in body_text.lower() for sig in FATAL_SIGNATURES):
                    console_log(email_addr, "CDN 403 拦截，IP 已被封禁，直接失败", "error")
                    logger.error("CloudFront 403 拦截，停止登录")
                    return "rate_limited"

                _dismiss_error_popup(page, logger)
                if ("网络连接失败" in body_text or "208075" in body_text) and iteration < 5:
                    msg = "尝试刷新页面..."
                    logger.info(msg)
                    try:
                        page.reload(timeout=10000)
                    except Exception:
                        pass
                    page.wait_for_timeout(random.randint(2500, 3500))
                    continue
                # 300010 等临时性错误，点击"已知晓"后继续
                if any(sig in body_text for sig in RETRIABLE_SIGNATURES):
                    console_log(email_addr, "临时错误，点击已知晓后继续", "warning")
                    logger.warning("临时错误 (RETRIABLE)，继续重试")
                    page.wait_for_timeout(random.randint(2000, 4000))
                    continue
        except Exception as e:
            msg = f"迭代 {iteration + 1} 异常: {e}"
            logger.error(msg)
            import traceback
            stack = traceback.format_exc()
            logger.error(f"堆栈: {stack}")
            continue

        if "/login/stay-signed-in" in url:
            last_stage = "stay-signed-in"
            console_log(email_addr, "stay-signed-in: 点击保持登录")
            logger.info("stay-signed-in - 点击'是'按钮")
            url_before = url

            # 尝试点击按钮
            clicked = click_button(page, ["是", "Yes", "确定", "OK", "保持登录", "Stay signed in"])
            if not clicked:
                # 如果没找到按钮，尝试点击页面中心
                logger.info("未找到按钮，尝试点击页面")
                try:
                    page.click("body", position={"x": 400, "y": 300})
                except Exception:
                    pass

            url = _check_url_change(page, url_before, "点击'是'按钮", 1500)
            continue

        if "/login/mfa" in url:
            last_stage = "mfa"
            console_log(email_addr, "mfa: 处理邮件验证码")
            logger.info("mfa - 处理邮件验证码")
            url_before = url
            try:
                ok = handle_email_verification(
                    page,
                    imap_host,
                    imap_port,
                    email_addr,
                    email_password,
                    initial_mail_count,
                    mfa_submit_retry=mfa_config.get("submit_retry", 2),
                    consumed_codes=consumed_codes,
                    expected_url_pattern="/login/mfa",
                )
                # 处理 IMAP 认证失败
                if ok == "imap_auth_failed":
                    logger.info("IMAP 认证失败，邮箱未开启 IMAP 或密码错误，无法读取邮件")
                    save_failure_log(logger, email_addr)
                    return "imap_auth_failed"
                # 处理 URL 跳转的情况
                if ok == "url_changed":
                    logger.info("邮件验证期间检测到 URL 跳转，继续状态机")
                    continue
                if not ok:
                    url_now = page.url
                    if "/my/" in url_now or "authcenter" in url_now or "/login/stay-signed-in" in url_now:
                        logger.info("邮件验证返回失败但页面已跳转，判定成功")
                        continue
                    console_log(email_addr, "邮件验证失败，刷新重试", "warning")
                    logger.warning("邮件验证失败，刷新页面重试")
                    try:
                        page.reload(timeout=10000)
                    except Exception:
                        pass
                    page.wait_for_timeout(2000)
                    continue
            except Exception as e:
                logger.info(f"handle_email_verification 异常: {e}")
                import traceback
                logger.info(f"堆栈: {traceback.format_exc()}")
                url_now = page.url
                if "/my/" in url_now or "authcenter" in url_now or "/login/stay-signed-in" in url_now:
                    logger.info("异常但页面已跳转，判定成功")
                    continue
                try:
                    page.reload(timeout=10000)
                except Exception:
                    pass
                page.wait_for_timeout(2000)
                continue

            page.wait_for_timeout(random.randint(2200, 3200))
            url_after = page.url
            if "/my/" in url_after or "/login/stay-signed-in" in url_after:
                mfa_retry_count = 0
                continue

            if url_after == url_before or "/login/mfa" in url_after:
                # Only go to register flow if explicit not-registered signals are present.
                if need_register(page):
                    console_log(email_addr, "检测到账号未注册，跳转注册")
                    logger.info("检测到账号未注册")
                    return "need_register"

                mfa_retry_count += 1
                console_log(email_addr, f"MFA重试 #{mfa_retry_count}", "warning")
                logger.info(f"MFA 提交后仍停留在当前页，重试次数: {mfa_retry_count}")
                if mfa_retry_count >= MAX_MFA_RETRIES:
                    has_risk_now, _ = _has_risk_error(page)
                    if has_risk_now:
                        return "rate_limited"
                    return False
                continue

            mfa_retry_count = 0
            continue

        if "/login/password" in url:
            last_stage = "password"
            console_log(email_addr, "password: 输入密码")
            logger.info("password - 输入密码")
            url_before = url

            # 检查并点击"已知晓"按钮
            _dismiss_error_popup(page)

            try:
                initial_mail_count = get_initial_mail_count(imap_host, imap_port, email_addr, email_password)
                if initial_mail_count == "imap_auth_failed":
                    logger.info("IMAP 认证失败，邮箱未开启 IMAP 或密码错误，无法读取邮件")
                    save_failure_log(logger, email_addr)
                    return "imap_auth_failed"
                logger.info(f"获取初始邮件数: {initial_mail_count}")
            except Exception as e:
                logger.info(f"获取初始邮件数失败: {e}")
                initial_mail_count = 0

            try:
                input_password(page, email_password)
                page.wait_for_timeout(random.randint(400, 600))
                click_button(page, ["继续", "Continue", "下一步", "Next"])

                # 等待页面响应（URL变化或验证码弹窗）
                response_type, url = _wait_for_page_response(page, url_before, timeout_ms=5000, logger=logger)
                logger.info(f"密码页点击继续后响应类型: {response_type}")

            except Exception as e:
                logger.info(f"输入密码或点击继续失败: {e}")
                import traceback
                logger.info(f"堆栈: {traceback.format_exc()}")
                continue

            captcha_result = solve_captcha_if_present(
                page,
                api_key,
                model,
                email_addr,
                captcha_config=captcha_config,
                reload_url=login_start_url,
                page_timeout=page_timeout,
            )
            should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
                captcha_result, captcha_fail_count, email_addr, logger
            )
            if should_stop:
                return stop_reason
            if captcha_result is False:
                continue

            # 验证码处理后等待URL变化（最多等待3秒）
            changed, url = _wait_for_url_change(page, url, timeout_ms=3000, logger=logger)
            continue

        if "/login" in url and "/login/" not in url:
            url_before = url

            # 检查并点击"已知晓"按钮
            _dismiss_error_popup(page, logger)

            captcha_result = solve_captcha_if_present(
                page,
                api_key,
                model,
                email_addr,
                captcha_config=captcha_config,
                reload_url=login_start_url,
                page_timeout=page_timeout,
            )
            should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
                captcha_result, captcha_fail_count, email_addr, logger
            )
            if should_stop:
                return stop_reason
            if captcha_result is not True:
                if captcha_result is False:
                    continue
                # 验证码处理后等待URL变化
                changed, url = _wait_for_url_change(page, url_before, timeout_ms=3000, logger=logger)
                continue

            # 验证码处理成功后，等待URL变化（最多等待5秒）
            changed, url = _wait_for_url_change(page, url_before, timeout_ms=5000, logger=logger)
            if changed:
                # URL已经变化，跳到下一次迭代处理新的URL状态
                logger.info(f"验证码处理后URL已变化，进入新状态: {url}")
                continue

            email_input = page.query_selector("input[data-e2e='input-username'], input[name='username'], input[name='email']")
            if email_input:
                try:
                    current_value = email_input.input_value()
                    logger.info(f"邮箱输入框当前值: {current_value}")
                except Exception as e:
                    logger.info(f"获取邮箱输入框值失败: {e}")
                    current_value = ""
                if current_value and email_addr in current_value:
                    logger.info("邮箱已输入，点击继续...")
                    click_login_continue_strict(page)

                    # 等待页面响应（URL变化或验证码弹窗）
                    response_type, url = _wait_for_page_response(page, url_before, timeout_ms=5000, logger=logger)
                    logger.info(f"邮箱已输入点击继续后响应类型: {response_type}")

                    # 检查并点击"已知晓"按钮
                    _dismiss_error_popup(page, logger)

                    # 检查页面是否提示未注册
                    if need_register(page):
                        console_log(email_addr, "账号未注册，跳转注册流程")
                        logger.info("页面提示账号未注册，跳转到注册流程")
                        return "need_register"

                    if "/login/password" not in url and "/login/mfa" not in url and "/my/" not in url:
                        # 可能是验证码错误，继续重试而不是直接判断未注册
                        logger.info("邮箱+验证码完成后未进入密码页，继续重试...")
                    continue

            console_log(email_addr, "login: 输入邮箱")
            last_stage = "login"
            input_email(page, email_addr)
            page.wait_for_timeout(random.randint(400, 600))
            click_login_continue_strict(page)

            # 等待页面响应（URL变化或验证码弹窗）
            response_type, url = _wait_for_page_response(page, url_before, timeout_ms=5000, logger=logger)
            logger.info(f"登录页输入邮箱后响应类型: {response_type}")

            # 检查并点击"已知晓"按钮
            _dismiss_error_popup(page, logger)

            # 检查页面是否提示未注册
            if need_register(page):
                console_log(email_addr, "账号未注册，跳转注册流程")
                logger.info("页面提示账号未注册，跳转到注册流程")
                return "need_register"

            if "/login/password" not in url and "/login/mfa" not in url and "/my/" not in url:
                # 先再做一次验证码处理
                post_captcha_result = solve_captcha_if_present(
                    page,
                    api_key,
                    model,
                    email_addr,
                    captcha_config=captcha_config,
                    reload_url=login_start_url,
                    page_timeout=page_timeout,
                )
                should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
                    post_captcha_result, captcha_fail_count, email_addr, logger
                )
                if should_stop:
                    return stop_reason
                if post_captcha_result is False:
                    continue
                # 验证码处理后等待URL变化
                changed, url = _wait_for_url_change(page, url, timeout_ms=5000, logger=logger)
                if "/login/password" not in url and "/login/mfa" not in url and "/my/" not in url:
                    # 检查是否有明确的未注册提示
                    if need_register(page):
                        console_log(email_addr, "检测到账号未注册，跳转注册")
                        logger.info("检测到账号未注册")
                        return "need_register"
                    # 否则继续重试，可能是验证码错误
                    logger.info("验证码可能错误，继续重试...")
                    continue

            if need_register(page):
                console_log(email_addr, "检测到账号未注册，跳转注册")
                logger.info("检测到账号未注册")
                return "need_register"
            continue

        if need_register(page):
            console_log(email_addr, "检测到账号未注册，跳转注册")
            logger.info("检测到账号未注册")
            return "need_register"

        url_before = url
        captcha_result = solve_captcha_if_present(
            page,
            api_key,
            model,
            email_addr,
            captcha_config=captcha_config,
            reload_url=login_start_url,
            page_timeout=page_timeout,
        )
        should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
            captcha_result, captcha_fail_count, email_addr, logger
        )
        if should_stop:
            return stop_reason
        if captcha_result is False:
            continue

        # 验证码处理后等待URL变化（最多等待3秒）
        changed, url = _wait_for_url_change(page, url_before, timeout_ms=3000, logger=logger)

    duration = (datetime.now() - start_time).total_seconds()
    logger.warning("登录流程超过最大总迭代次数")
    log_summary(email_addr, False, duration, stage=last_stage, iterations=MAX_TOTAL_ITERATIONS, extra_info="总迭代超时")
    save_failure_log(logger, email_addr)
    return False


def register_with_url_state(page, email_addr, email_password, config, page_timeout=60000):
    # 设置日志
    logger = setup_logger(email_addr)
    start_time = datetime.now()
    logger.info(f"开始注册: {email_addr}")

    api_key = config["openrouter_api_key"]
    model = config.get("models", [])
    imap_host = config["imap_host"]
    imap_port = config["imap_port"]

    # 添加请求监控（调试风控）—— 用事件监听，不用 route 拦截，避免与缓存路由冲突
    request_log = []
    def log_request(request):
        if "binance.com" in request.url:
            req_info = {
                "time": datetime.now().strftime("%H:%M:%S.%f")[:-3],
                "method": request.method,
                "url": request.url[:100],
            }
            if any(keyword in request.url for keyword in ["precheck", "getCaptcha", "validateCaptcha", "bizCheck", "check/result"]):
                req_info["full_url"] = request.url
                req_info["headers"] = {
                    "user-agent": request.headers.get("user-agent", "")[:50],
                    "referer": request.headers.get("referer", ""),
                    "x-trace-id": request.headers.get("x-trace-id", ""),
                    "clienttype": request.headers.get("clienttype", ""),
                }
            request_log.append(req_info)

    def log_response(response):
        if "binance.com" in response.url and response.status >= 400:
            logger.warning(f"错误响应: {response.status} {response.url[:100]}")
            try:
                body = response.text()
                if "208061" in body or "208075" in body or "frequency" in body.lower():
                    logger.error(f"风控响应内容: {body[:500]}")
            except Exception:
                pass

    def cleanup_listeners():
        """清理页面事件监听器（只移除自己注册的，不动 route）"""
        try:
            page.remove_listener("request", log_request)
            page.remove_listener("response", log_response)
        except Exception:
            pass

    page.on("request", log_request)
    page.on("response", log_response)

    console_log(email_addr, "开始注册")
    logger.info("打开注册页面...")
    if not goto_with_retry(page, "https://accounts.binance.com/zh-CN/register", page_timeout=page_timeout):
        console_log(email_addr, "注册页面加载失败", "error")
        logger.error("注册页面加载失败")
        cleanup_listeners()
        return False

    # 模拟真实用户：页面加载后的自然行为
    try:
        # 等待页面完全加载
        page.wait_for_timeout(random.randint(2000, 4000))

        # 随机移动鼠标（模拟浏览页面，贝塞尔曲线）
        for _ in range(random.randint(3, 6)):
            x = random.randint(200, 1000)
            y = random.randint(200, 700)
            _bezier_mouse_move(page, x, y)
            page.wait_for_timeout(random.randint(300, 800))

        # 随机滚动页面
        scroll_amount = random.randint(-100, 100)
        page.evaluate(f"window.scrollBy(0, {scroll_amount})")
        page.wait_for_timeout(random.randint(500, 1500))

        logger.info("完成页面浏览行为模拟")
    except Exception as e:
        logger.info(f"页面行为模拟异常: {e}")

    initial_mail_count = get_initial_mail_count(imap_host, imap_port, email_addr, email_password)
    if initial_mail_count == "imap_auth_failed":
        logger.info("IMAP 认证失败，邮箱未开启 IMAP 或密码错误，无法读取邮件")
        save_failure_log(logger, email_addr)
        return "imap_auth_failed"
    consumed_codes = set()
    captcha_fail_count = 0  # 验证码连续失败计数

    # URL 状态计数器
    url_retry_counts = {}  # {url_pattern: count}
    last_url_pattern = None

    def _get_url_pattern(url):
        """提取 URL 的状态模式"""
        if "/register/verification" in url or "/verification-new-register" in url:
            return "register_verification"
        elif "/register/register-set-password" in url or "/register-set-password" in url:
            return "register_password"
        elif "/invite" in url:
            return "invite"
        elif "/register" in url and "/register/" not in url:
            return "register"
        elif "/my/" in url:
            return "dashboard"
        else:
            return "other"

    for iteration in range(MAX_TOTAL_ITERATIONS):
        # 变速等待：基础随机 + 偶尔长停顿，避免固定节奏
        base_wait = random.randint(1200, 3200)
        if random.random() < 0.15:  # 15% 概率长停顿
            base_wait += random.randint(1500, 4000)
        page.wait_for_timeout(base_wait)
        url = page.url
        url_pattern = _get_url_pattern(url)

        # 检查 URL 状态是否变化
        if url_pattern == last_url_pattern:
            url_retry_counts[url_pattern] = url_retry_counts.get(url_pattern, 0) + 1
            if url_retry_counts[url_pattern] >= MAX_URL_RETRIES:
                logger.warning(f"URL 状态 {url_pattern} 重试次数超过 {MAX_URL_RETRIES} 次，停止")
                console_log(email_addr, f"{url_pattern} 重试超限", "error")
                duration = (datetime.now() - start_time).total_seconds()
                log_summary(email_addr, False, duration, stage="register", iterations=iteration+1, extra_info=f"{url_pattern}超限")
                save_failure_log(logger, email_addr)
                cleanup_listeners()
                return False
        else:
            # URL 状态变化，重置该状态的计数
            url_retry_counts[url_pattern] = 1
            last_url_pattern = url_pattern

        logger.info(f"注册迭代 {iteration + 1} URL状态: {url_pattern} (重试 {url_retry_counts.get(url_pattern, 1)}/{MAX_URL_RETRIES})")

        # 检测风控错误（208061/208075 等频率限制）
        has_risk, body_text = _has_risk_error(page, logger)
        if has_risk:
            console_log(email_addr, "检测到风控错误", "warning")
            logger.warning(f"风控错误，页面内容: {body_text[:300]}")

            # CloudFront 403 等 CDN 层拦截，直接失败不重试
            if any(sig.lower() in body_text.lower() for sig in FATAL_SIGNATURES):
                console_log(email_addr, "CDN 403 拦截，IP 已被封禁，直接失败", "error")
                logger.error("CloudFront 403 拦截，停止注册")
                duration = (datetime.now() - start_time).total_seconds()
                log_summary(email_addr, False, duration, stage="register", extra_info="CDN 403拦截")
                save_failure_log(logger, email_addr)
                cleanup_listeners()
                return "rate_limited"

            _dismiss_error_popup(page, logger)

            # 对特定错误码进行重试（类似登录流程）
            if ("208075" in body_text or "208061" in body_text or "网络连接失败" in body_text) and iteration < 5:
                console_log(email_addr, "尝试刷新页面重试", "warning")
                logger.warning("临时风控错误，刷新页面重试")
                try:
                    page.reload(timeout=10000)
                except Exception:
                    pass
                # 更长的冷却时间
                page.wait_for_timeout(random.randint(5000, 8000))
                continue

            # 300010 等临时性错误，点击"已知晓"后继续（不刷新页面）
            if any(sig in body_text for sig in RETRIABLE_SIGNATURES):
                console_log(email_addr, "临时错误，点击已知晓后继续", "warning")
                logger.warning(f"临时错误 (RETRIABLE)，继续重试")
                page.wait_for_timeout(random.randint(2000, 4000))
                continue

            # 其他风控错误才返回失败
            console_log(email_addr, "检测到严重风控错误，停止注册", "error")
            logger.error("严重风控错误，停止注册")

            # 输出最近的请求日志
            logger.error("=== 最近10个请求 ===")
            for req in request_log[-10:]:
                logger.error(f"{req['time']} {req['method']} {req['url']}")
                if 'headers' in req:
                    logger.error(f"  Headers: {req['headers']}")
                if 'full_url' in req:
                    logger.error(f"  Full URL: {req['full_url']}")

            duration = (datetime.now() - start_time).total_seconds()
            log_summary(email_addr, False, duration, stage="register", extra_info="风控限制")
            save_failure_log(logger, email_addr)
            cleanup_listeners()
            return "rate_limited"

        # 检测白屏（类似登录流程）
        if _is_page_blank(page, logger):
            console_log(email_addr, "检测到白屏，刷新页面", "warning")
            logger.warning("检测到白屏，刷新页面")
            try:
                page.reload(timeout=10000)
            except Exception:
                pass
            page.wait_for_timeout(2000)
            continue

        # 检测"已存在账户"弹窗（账号已注册）
        try:
            body_text = page.inner_text("body")
            if "已经存在账户" in body_text or "已存在账户" in body_text or "account already exists" in body_text.lower():
                # 尝试关闭弹窗
                close_buttons = [
                    "button:has-text('关闭')",
                    "button:has-text('Close')",
                    "[aria-label='Close']",
                    ".close",
                    "button:has-text('取消')",
                    "button:has-text('Cancel')",
                ]
                for selector in close_buttons:
                    try:
                        btn = page.query_selector(selector)
                        if btn and btn.is_visible():
                            btn.click()
                            page.wait_for_timeout(500)
                            break
                    except Exception:
                        pass
                console_log(email_addr, "账号已注册", "warning")
                logger.info("检测到账号已注册弹窗")
                duration = (datetime.now() - start_time).total_seconds()
                log_summary(email_addr, False, duration, stage="register", extra_info="已注册")
                cleanup_listeners()
                return "already_registered"
        except Exception:
            pass

        if "/invite" in url:
            console_log(email_addr, "invite: 点击下一步")
            logger.info("invite - 点击下一步")
            url_before = url
            click_button(page, ["下一步", "Next", "跳过", "Skip"])
            # 等待URL变化（最多等待3秒）
            changed, url = _wait_for_url_change(page, url_before, timeout_ms=3000, logger=logger)
            continue

        if "/register/register-set-password" in url or "/register-set-password" in url:
            console_log(email_addr, "set-password: 输入密码")
            logger.info("set-password - 输入密码")
            url_before = url

            # 等待页面稳定，避免导航中 context 被销毁
            try:
                page.wait_for_load_state("domcontentloaded", timeout=5000)
            except Exception:
                pass
            page.wait_for_timeout(random.randint(800, 1500))

            try:
                input_password(page, email_password)
            except Exception as e:
                logger.warning(f"输入密码异常: {e}，等待页面稳定后重试")
                page.wait_for_timeout(2000)
                try:
                    input_password(page, email_password)
                except Exception as e2:
                    logger.error(f"重试输入密码仍失败: {e2}")
                    continue

            page.wait_for_timeout(random.randint(400, 600))
            click_button(page, ["继续", "Continue", "下一步", "Next"])

            # 等待页面响应（URL变化 或 验证码弹窗）
            response_type, url = _wait_for_page_response(page, url_before, timeout_ms=5000, logger=logger)
            logger.info(f"密码页点击继续后响应类型: {response_type}")

            # 验证码弹窗 → 直接处理
            if response_type == "captcha":
                captcha_result = solve_captcha_if_present(page, api_key, model, email_addr)
            else:
                # URL变化或超时，也检测一次验证码（可能延迟弹出）
                captcha_result = solve_captcha_if_present(page, api_key, model, email_addr)

            should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
                captcha_result, captcha_fail_count, email_addr, logger
            )
            if should_stop:
                cleanup_listeners()
                return stop_reason
            if captcha_result is False:
                cooldown = random.randint(8000, 15000)
                console_log(email_addr, f"验证码失败，冷却 {cooldown/1000:.1f}秒", "warning")
                page.wait_for_timeout(cooldown)

            # 验证码处理后等待URL变化（增加到10秒，验证码服务器验证+跳转需要时间）
            changed, url_after = _wait_for_url_change(page, url, timeout_ms=10000, logger=logger)

            # 如果验证码通过但URL仍然是密码页，需要细分原因
            if captcha_result is True and ("/register/register-set-password" in url_after or "/register-set-password" in url_after):
                console_log(email_addr, "验证码通过但页面未跳转，检查原因...", "warning")
                logger.warning("验证码通过但页面停留在密码页，进一步检查")

                # ── 优先检查是否是"已注册"弹窗 ────────────────────────
                page.wait_for_timeout(1500)
                already_reg_selectors = [
                    "text=账号已存在",
                    "text=该邮箱已注册",
                    "text=Email already",
                    "text=already registered",
                    "text=already exists",
                    "text=208001",  # Binance 已注册错误码
                ]
                for sel in already_reg_selectors:
                    try:
                        el = page.query_selector(sel)
                        if el and el.is_visible():
                            console_log(email_addr, "检测到已注册提示，标记为已注册", "warning")
                            logger.info(f"密码页检测到已注册: {sel}")
                            _dismiss_error_popup(page, logger)
                            duration = (datetime.now() - start_time).total_seconds()
                            log_summary(email_addr, False, duration, stage="register", extra_info="已注册")
                            cleanup_listeners()
                            return "already_registered"
                    except Exception:
                        pass

                # ── 再等 3 秒，给页面跳转最后机会 ────────────────────
                changed2, url_after2 = _wait_for_url_change(page, url_after, timeout_ms=3000, logger=logger)
                if changed2:
                    logger.info(f"延迟跳转成功: {url_after2}")
                    url_after = url_after2
                else:
                    # ── 确认是否真的有风控错误 ───────────────────────
                    has_risk_now, body_text = _has_risk_error(page, logger)
                    if has_risk_now:
                        console_log(email_addr, "确认触发风控，停止注册", "error")
                        logger.error(f"风控错误内容: {body_text[:300]}")
                        duration = (datetime.now() - start_time).total_seconds()
                        log_summary(email_addr, False, duration, stage="register", extra_info="验证码后风控")
                        save_failure_log(logger, email_addr)
                        cleanup_listeners()
                        return "rate_limited"
                    else:
                        # 无风控错误，可能只是页面慢，继续状态机下一轮
                        console_log(email_addr, "无风控错误，继续等待跳转", "warning")
                        logger.warning("密码页未跳转但无风控错误，继续状态机")
                        url_after = page.url

            url = url_after
            continue

        if "/register/verification" in url or "/verification-new-register" in url:
            console_log(email_addr, "verification: 处理邮件验证码")
            logger.info("verification - 处理邮件验证码")
            url_before = url
            result = handle_email_verification(
                page,
                imap_host,
                imap_port,
                email_addr,
                email_password,
                initial_mail_count,
                consumed_codes=consumed_codes,
                expected_url_pattern="/register/verification",
            )
            # 处理 IMAP 认证失败
            if result == "imap_auth_failed":
                logger.info("IMAP 认证失败，邮箱未开启 IMAP 或密码错误，无法读取邮件")
                cleanup_listeners()
                save_failure_log(logger, email_addr)
                return "imap_auth_failed"
            # 处理 URL 跳转的情况
            if result == "url_changed":
                logger.info("邮件验证期间检测到 URL 跳转，继续状态机")
                url = page.url
                continue
            if not result:
                logger.error("邮件验证失败")
                cleanup_listeners()
                return False
            # 等待URL变化（最多等待5秒）
            changed, url = _wait_for_url_change(page, url_before, timeout_ms=5000, logger=logger)
            continue

        if "/register" in url and "/register/" not in url:
            console_log(email_addr, "register: 输入邮箱")
            logger.info("register - 输入邮箱")
            url_before = url

            # 模拟真实用户行为：贝塞尔曲线鼠标移动
            try:
                for _ in range(random.randint(2, 4)):
                    x = random.randint(100, 800)
                    y = random.randint(100, 600)
                    _bezier_mouse_move(page, x, y)
                    page.wait_for_timeout(random.randint(200, 500))

                # 随机滚动页面
                page.evaluate(f"window.scrollBy(0, {random.randint(-50, 50)})")
                page.wait_for_timeout(random.randint(300, 800))
            except Exception:
                pass

            input_email(page, email_addr)
            page.wait_for_timeout(random.randint(400, 600))

            # 勾选"创建账户即表示您同意币安"复选框
            _tick_agreement_checkbox(page, email_addr, logger)

            page.wait_for_timeout(random.randint(400, 600))
            initial_mail_count = get_initial_mail_count(imap_host, imap_port, email_addr, email_password)
            if initial_mail_count == "imap_auth_failed":
                logger.info("IMAP 认证失败，邮箱未开启 IMAP 或密码错误，无法读取邮件")
                save_failure_log(logger, email_addr)
                return "imap_auth_failed"
            click_button(page, ["继续", "Continue", "下一步", "Next"])

            # 等待页面响应（URL变化 或 验证码弹窗）
            response_type, url = _wait_for_page_response(page, url_before, timeout_ms=5000, logger=logger)
            logger.info(f"注册页点击继续后响应类型: {response_type}")

            # 验证码弹窗出现 → 直接处理验证码，不做其他操作
            if response_type == "captcha":
                captcha_result = solve_captcha_if_present(page, api_key, model, email_addr)
                should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
                    captcha_result, captcha_fail_count, email_addr, logger
                )
                if should_stop:
                    cleanup_listeners()
                    return stop_reason
                if captcha_result is False:
                    cooldown = random.randint(8000, 15000)
                    console_log(email_addr, f"验证码失败，冷却 {cooldown/1000:.1f}秒", "warning")
                    page.wait_for_timeout(cooldown)
                # 验证码处理后等待URL变化
                changed, url_after = _wait_for_url_change(page, url, timeout_ms=10000, logger=logger)
                url = url_after
                continue

            # URL 未变化 → 检查是否因未勾选协议而被拦截
            if response_type == "timeout":
                try:
                    body_text = page.inner_text("body")
                    if "您需同意" in body_text or "需同意" in body_text or "agree to" in body_text.lower():
                        console_log(email_addr, "未勾选协议，重新勾选", "warning")
                        logger.warning("检测到未勾选协议提示，重新勾选")
                        _tick_agreement_checkbox(page, email_addr, logger)
                        page.wait_for_timeout(random.randint(500, 800))
                        click_button(page, ["继续", "Continue", "下一步", "Next"])
                        response_type2, url = _wait_for_page_response(page, url_before, timeout_ms=5000, logger=logger)
                        if response_type2 == "captcha":
                            captcha_result = solve_captcha_if_present(page, api_key, model, email_addr)
                            should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
                                captcha_result, captcha_fail_count, email_addr, logger
                            )
                            if should_stop:
                                cleanup_listeners()
                                return stop_reason
                            if captcha_result is False:
                                cooldown = random.randint(8000, 15000)
                                console_log(email_addr, f"验证码失败，冷却 {cooldown/1000:.1f}秒", "warning")
                                page.wait_for_timeout(cooldown)
                            changed, url_after = _wait_for_url_change(page, url, timeout_ms=10000, logger=logger)
                            url = url_after
                            continue
                except Exception:
                    pass

                # 检查 300010 等临时性错误弹窗
                try:
                    body_text = page.inner_text("body")
                    if any(sig in body_text for sig in RETRIABLE_SIGNATURES):
                        console_log(email_addr, "检测到临时错误弹窗，点击已知晓", "warning")
                        logger.warning(f"检测到临时错误: {[s for s in RETRIABLE_SIGNATURES if s in body_text]}")
                        _dismiss_error_popup(page, logger)
                        page.wait_for_timeout(random.randint(2000, 4000))
                        continue
                except Exception:
                    pass

                # 超时但无特殊情况，尝试一次验证码检测（可能弹窗延迟出现）
                captcha_result = solve_captcha_if_present(page, api_key, model, email_addr)
                should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
                    captcha_result, captcha_fail_count, email_addr, logger
                )
                if should_stop:
                    cleanup_listeners()
                    return stop_reason
                if captcha_result is False:
                    cooldown = random.randint(8000, 15000)
                    console_log(email_addr, f"验证码失败，冷却 {cooldown/1000:.1f}秒", "warning")
                    page.wait_for_timeout(cooldown)

            # URL 已变化或验证码处理完毕，等待最终跳转
            changed, url_after = _wait_for_url_change(page, url, timeout_ms=10000, logger=logger)
            if captcha_result is True and "/register" in url_after and "/register/" not in url_after:
                console_log(email_addr, "验证码通过但页面未跳转，检查是否风控", "warning")
                logger.warning("验证码通过但页面回到注册页，检查页面内容")

                # 检查页面是否有风控错误
                page.wait_for_timeout(2000)  # 等待错误信息加载
                has_risk_now, body_text = _has_risk_error(page, logger)
                if has_risk_now:
                    console_log(email_addr, "确认触发风控，停止注册", "error")
                    logger.error(f"风控错误内容: {body_text[:500]}")

                    # 输出最近的请求日志
                    logger.error("=== 最近10个请求 ===")
                    for req in request_log[-10:]:
                        logger.error(f"{req['time']} {req['method']} {req['url']}")
                        if 'headers' in req:
                            logger.error(f"  Headers: {req['headers']}")
                        if 'full_url' in req:
                            logger.error(f"  Full URL: {req['full_url']}")

                    duration = (datetime.now() - start_time).total_seconds()
                    log_summary(email_addr, False, duration, stage="register", extra_info="验证码后风控")
                    save_failure_log(logger, email_addr)
                    cleanup_listeners()
                    return "rate_limited"
                else:
                    # 可能只是页面跳转慢，继续下一轮
                    console_log(email_addr, "未检测到风控错误，继续尝试", "warning")
                    logger.warning("页面未跳转但无风控错误，继续")

            url = url_after
            continue

        if "/my/" in url or ("binance.com" in url and "register" not in url and "login" not in url):
            duration = (datetime.now() - start_time).total_seconds()
            logger.info("注册成功!")
            log_summary(email_addr, True, duration, stage="dashboard", iterations=iteration+1)
            cleanup_listeners()
            return True

        url_before = url
        captcha_result = solve_captcha_if_present(page, api_key, model, email_addr)
        should_stop, captcha_fail_count, stop_reason = _handle_captcha_result(
            captcha_result, captcha_fail_count, email_addr, logger
        )
        if should_stop:
            cleanup_listeners()
            return stop_reason
        if captcha_result is False:
            continue

        # 验证码处理后等待URL变化（最多等待3秒）
        changed, url = _wait_for_url_change(page, url_before, timeout_ms=3000, logger=logger)

    duration = (datetime.now() - start_time).total_seconds()
    logger.warning("注册流程超过最大总迭代次数")
    log_summary(email_addr, False, duration, stage="register", iterations=MAX_TOTAL_ITERATIONS, extra_info="总迭代超时")
    save_failure_log(logger, email_addr)
    cleanup_listeners()
    return False
