"""页面状态与风险信号检测。

封装 URL 状态、风控关键词、代理错误和认证失败判断，供登录/注册流程复用。
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from urllib.parse import urlsplit


DASHBOARD_URL = "https://www.binance.com/zh-CN/my/dashboard"

RISK_SIGNATURES = (
    "网络连接失败",
    "操作失败",
    "PRECHECK",
    "cap_too_many_attempts",
    "208075",
    "208061",
    "认证失败，请刷新页面后重试",
    "$e.execute is not a function",
    "403 ERROR",
    "The request could not be satisfied",
    "Generated by cloudfront",
    "无法为该地区的用户提供服务",
    "200004431",
    "300010",
)

AUTH_FAILURE_SIGNATURES = (
    "认证失败，请刷新页面后重试",
)

AUTH_FAILURE_CONTINUE_BUTTONS = (
    "继续",
    "Continue",
    "下一步",
    "Next",
    "重试",
    "Retry",
    "Try again",
    "已知晓",
    "Got it",
    "确定",
    "OK",
)

PROXY_FAILURE_SIGNATURES = (
    "407 Proxy Authentication Required",
    "Proxy Authentication Required",
    "ERR_PROXY_CONNECTION_FAILED",
    "ERR_TUNNEL_CONNECTION_FAILED",
    "代理认证失败",
    "代理连接失败",
)

FREQUENCY_LIMIT_SIGNATURES = (
    "frequency limit",
    "208061",
)

ALREADY_REGISTERED_SIGNATURES = (
    "已经存在账户",
    "已存在账户",
    "账户已经存在",
    "账号已注册",
    "该邮箱已注册",
    "account already exists",
    "email already registered",
    "already registered",
)

RETRIABLE_SIGNATURES = (
    "300010",
)

FATAL_SIGNATURES = (
    "403 ERROR",
    "The request could not be satisfied",
    "Generated by cloudfront",
    "无法为该地区的用户提供服务",
    "200004431",
    "PRECHECK",
)


class UrlState(str, Enum):
    """页面 URL 所处的业务状态。"""

    LOGIN = "login"
    LOGIN_PASSWORD = "login_password"
    LOGIN_MFA = "login_mfa"
    LOGIN_STAY_SIGNED_IN = "login_stay_signed_in"
    REGISTER = "register"
    REGISTER_VERIFICATION = "register_verification"
    REGISTER_PASSWORD = "register_password"
    INVITE = "invite"
    DASHBOARD = "dashboard"
    CALLBACK = "callback"
    OTHER = "other"


@dataclass(frozen=True)
class RiskAssessment:
    """页面风险检测结果。"""

    has_risk: bool
    text: str
    is_fatal: bool
    is_auth_failure: bool
    is_proxy_failure: bool
    is_retriable: bool


def _contains_any(text: str, signatures: tuple[str, ...]) -> bool:
    normalized = str(text or "").lower()
    return any(signature.lower() in normalized for signature in signatures)


def is_browser_network_error_url(url: str) -> bool:
    """判断 URL 是否为浏览器网络错误页。"""
    return str(url or "").startswith("chrome-error://")


def is_logged_in_url(url: str) -> bool:
    """判断 URL 是否表示已进入登录态页面。"""
    try:
        parsed = urlsplit(str(url or ""))
    except Exception:
        return False

    hostname = str(parsed.hostname or "").lower()
    path = str(parsed.path or "").lower()
    if hostname not in {"www.binance.com", "binance.com"}:
        return False
    if path.endswith("/my") or "/my/" in path:
        return True
    success_markers = (
        "/dashboard",
        "/kyc",
        "/identity",
        "/usercenter/identity",
    )
    return any(path == marker or marker in path for marker in success_markers)


def is_dashboard_url(url: str) -> bool:
    """判断 URL 是否为 dashboard。"""
    try:
        parsed = urlsplit(str(url or ""))
    except Exception:
        return False

    hostname = str(parsed.hostname or "").lower()
    path = str(parsed.path or "").lower()
    return hostname in {"www.binance.com", "binance.com"} and "/my/dashboard" in path


def detect_login_url_state(url: str) -> UrlState:
    """识别登录流程的 URL 状态。"""
    value = str(url or "")
    if "/login/mfa" in value:
        return UrlState.LOGIN_MFA
    if "/login/password" in value:
        return UrlState.LOGIN_PASSWORD
    if "/login/stay-signed-in" in value:
        return UrlState.LOGIN_STAY_SIGNED_IN
    if "/login" in value and "/login/" not in value:
        return UrlState.LOGIN
    if "/my/" in value:
        return UrlState.DASHBOARD
    if "authcenter/callback" in value:
        return UrlState.CALLBACK
    return UrlState.OTHER


def detect_register_url_state(url: str) -> UrlState:
    """识别注册流程的 URL 状态。"""
    value = str(url or "")
    if "/register/verification" in value or "/verification-new-register" in value:
        return UrlState.REGISTER_VERIFICATION
    if "/register/register-set-password" in value or "/register-set-password" in value:
        return UrlState.REGISTER_PASSWORD
    if "/invite" in value:
        return UrlState.INVITE
    if "/register" in value and "/register/" not in value:
        return UrlState.REGISTER
    if "/my/" in value:
        return UrlState.DASHBOARD
    return UrlState.OTHER


def has_proxy_failure_error(text: str) -> bool:
    """判断文本是否包含代理失败信号。"""
    return _contains_any(text, PROXY_FAILURE_SIGNATURES)


def has_auth_failure_error(text: str) -> bool:
    """判断文本是否包含平台认证失败信号。"""
    return _contains_any(text, AUTH_FAILURE_SIGNATURES)


def has_frequency_limit_error(text: str) -> bool:
    """判断是否为平台频率限制弹窗，应立即结束当前账号流程。"""
    return _contains_any(text, FREQUENCY_LIMIT_SIGNATURES)


def has_already_registered_error(text: str) -> bool:
    """判断是否为注册页的已存在账户提示。"""
    return _contains_any(text, ALREADY_REGISTERED_SIGNATURES)


def assess_risk_text(text: str) -> RiskAssessment:
    """分析页面文本中的风险信号。"""
    value = str(text or "")
    is_proxy_failure = has_proxy_failure_error(value)
    is_auth_failure = has_auth_failure_error(value)
    return RiskAssessment(
        has_risk=_contains_any(value, RISK_SIGNATURES) or is_auth_failure or is_proxy_failure,
        text=value,
        is_fatal=_contains_any(value, FATAL_SIGNATURES),
        is_auth_failure=is_auth_failure,
        is_proxy_failure=is_proxy_failure,
        is_retriable=any(signature in value for signature in RETRIABLE_SIGNATURES),
    )
